### ISSUE TITLE
AsyncListTest breaks sometimes (maybe a bit flakey)

### ISSUE THREAD

**Issue by foundev** [datastax/stargate#127]
[ERROR] stargate.AsyncListTest.testLazyAppend  Time elapsed: 4.542 s  <<< FAILURE!
java.lang.AssertionError: assertion failed: 4539 < 4000+/-200
	at stargate.AsyncListTest.within(AsyncListTest.scala:43)
	at stargate.AsyncListTest.testLazyAppend(AsyncListTest.scala:79)

**Comment by stevedonnelly** [comment]
the test checks for lazy evaluation, using sleeps to represent a long running computation.  
instead of using timers to make sure things arent being evaluated eagerly, it should probably just increment and check an AtomicLong counter or something similar
